# Day 4 Pandas Concepts

Simple notes with a few clean examples. This notebook focuses on understanding the idea first.

In [1]:
import pandas as pd
from pathlib import Path

base_path = Path(".")
csv_path = base_path / "pokemonDB_dataset.csv"
json_path = base_path / "pokemonDB_dataset.json"

## 1. Series from a list

A `Series` is a one-dimensional labeled array. You can think of it like one column with an index.

In [2]:
data = [23, 13, 223, 232, 334, 23]
series = pd.Series(data, index=["a", "b", "c", "d", "e", "f"])

print(series)
print()
print(series[series > 200])

a     23
b     13
c    223
d    232
e    334
f     23
dtype: int64

c    223
d    232
e    334
dtype: int64

## 2. Series from a dictionary

When we use a dictionary, keys become the index labels.

In [3]:
portfolio = {"Day1": 100, "Day2": 300, "Day3": 200}
portfolio_series = pd.Series(portfolio)

print(portfolio_series)
print()
print("loc Day1 ->", portfolio_series.loc["Day1"])
print("iloc 1 ->", portfolio_series.iloc[1])

Day1    100
Day2    300
Day3    200
dtype: int64

loc Day1 -> 100
iloc 1 -> 300

## 3. DataFrame basics

A `DataFrame` is a 2D table with rows and columns.

In [4]:
students = pd.DataFrame({
    "Name": ["Person1", "Person2", "Person3"],
    "Age": [23, 24, 25],
})

students["Job"] = ["Cook", "Cashier", "Driver"]
new_row = pd.DataFrame([{"Name": "Person4", "Age": 24, "Job": "Scientist"}])
students = pd.concat([students, new_row], ignore_index=True)

students

      Name  Age        Job
0  Person1   23       Cook
1  Person2   24    Cashier
2  Person3   25     Driver
3  Person4   24  Scientist

## 4. Read CSV and JSON

CSV usually loads directly. This JSON file is nested, so `.T` makes it easier to read as rows.

In [5]:
pokemon_df = pd.read_csv(csv_path)
pokemon_json_df = pd.read_json(json_path).T.reset_index().rename(columns={"index": "Pokemon"})

print(pokemon_df.shape)
print(pokemon_json_df.shape)
pokemon_df.head(2)

(1219, 32)
(1215, 32)

,Pokemon,Type,Species,Height,Weight,Abilities,EV Yield,Catch Rate,Base Friendship,Base Exp,...,Defense Max,Special Attack Base,Special Attack Min,Special Attack Max,Special Defense Base,Special Defense Min,Special Defense Max,Speed Base,Speed Min,Speed Max
0,Abomasnow,"Grass, Ice",Frost Tree Pokémon,2.2 m (7′03″),135.5 kg (298.7 lbs),"1. Snow Warning, Soundproof (hidden ability)","1 Attack, 1 Sp. Atk","60 (7.8% with PokéBall, full HP)",50 (normal),173,...,273,92,170,311,85,157,295,60,112,240
1,Abomasnow,"Grass, Ice",Frost Tree Pokémon,2.2 m (7′03″),135.5 kg (298.7 lbs),"1. Snow Warning, Soundproof (hidden ability)","1 Attack, 1 Sp. Atk","60 (7.8% with PokéBall, full HP)",50 (normal),173,...,273,92,170,311,85,157,295,60,112,240

## 5. Quick look methods

Use these to quickly understand the data:
- `head()` -> first rows
- `tail()` -> last rows
- `info()` -> columns, non-null count, data types
- `describe()` -> summary stats

In [6]:
pokemon_df.head(3)

,Pokemon,Type,Species,Height,Weight,Abilities,EV Yield,Catch Rate,Base Friendship,Base Exp,...,Defense Max,Special Attack Base,Special Attack Min,Special Attack Max,Special Defense Base,Special Defense Min,Special Defense Max,Speed Base,Speed Min,Speed Max
0,Abomasnow,"Grass, Ice",Frost Tree Pokémon,2.2 m (7′03″),135.5 kg (298.7 lbs),"1. Snow Warning, Soundproof (hidden ability)","1 Attack, 1 Sp. Atk","60 (7.8% with PokéBall, full HP)",50 (normal),173,...,273,92,170,311,85,157,295,60,112,240
1,Abomasnow,"Grass, Ice",Frost Tree Pokémon,2.2 m (7′03″),135.5 kg (298.7 lbs),"1. Snow Warning, Soundproof (hidden ability)","1 Attack, 1 Sp. Atk","60 (7.8% with PokéBall, full HP)",50 (normal),173,...,273,92,170,311,85,157,295,60,112,240
2,Abomasnow,"Grass, Ice",Frost Tree Pokémon,2.2 m (7′03″),135.5 kg (298.7 lbs),"1. Snow Warning, Soundproof (hidden ability)","1 Attack, 1 Sp. Atk","60 (7.8% with PokéBall, full HP)",50 (normal),173,...,273,92,170,311,85,157,295,60,112,240

In [7]:
pokemon_df.tail(3)

,Pokemon,Type,Species,Height,Weight,Abilities,EV Yield,Catch Rate,Base Friendship,Base Exp,...,Defense Max,Special Attack Base,Special Attack Min,Special Attack Max,Special Defense Base,Special Defense Min,Special Defense Max,Speed Base,Speed Min,Speed Max
1216,Zygarde Complete Forme,"Dragon, Ground",Order Pokémon,4.5 m (14′09″),610.0 kg (1344.8 lbs),1. Power Construct,3 HP,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),319,...,375,91,168,309,95,175,317,85,157,295
1217,Zygarde Complete Forme,"Dragon, Ground",Order Pokémon,4.5 m (14′09″),610.0 kg (1344.8 lbs),1. Power Construct,3 HP,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),319,...,375,91,168,309,95,175,317,85,157,295
1218,Zygarde Complete Forme,"Dragon, Ground",Order Pokémon,4.5 m (14′09″),610.0 kg (1344.8 lbs),1. Power Construct,3 HP,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),319,...,375,91,168,309,95,175,317,85,157,295

In [8]:
pokemon_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1219 entries, 0 to 1218
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Pokemon               1219 non-null   str
 1   Type                  1219 non-null   str
 2   Species               1219 non-null   str
 3   Height                1219 non-null   str
 4   Weight                1219 non-null   str
 5   Abilities             1219 non-null   str
 6   EV Yield              1219 non-null   str
 7   Catch Rate            1219 non-null   str
 8   Base Friendship       1219 non-null   str
 9   Base Exp              1219 non-null   str
 10  Growth Rate           1219 non-null   str
 11  Egg Groups            1219 non-null   str
 12  Gender                1219 non-null   str
 13  Egg Cycles            1219 non-null   str
 14  HP Base               1219 non-null   int64
 15  HP Min                1219 non-null   int64
 16  HP Max                1219 non-null   int64
 17  Attack Base           1219 non-null   int64
 18  Attack Min            1219 non-null   int64
 19  Attack Max            1219 non-null   int64
 20  Defense Base          1219 non-null   int64
 21  Defense Min           1219 non-null   int64
 22  Defense Max           1219 non-null   int64
 23  Special Attack Base   1219 non-null   int64
 24  Special Attack Min    1219 non-null   int64
 25  Special Attack Max    1219 non-null   int64
 26  Special Defense Base  1219 non-null   int64
 27  Special Defense Min   1219 non-null   int64
 28  Special Defense Max   1219 non-null   int64
 29  Speed Base            1219 non-null   int64
 30  Speed Min             1219 non-null   int64
 31  Speed Max             1219 non-null   int64
dtypes: int64(18), str(14)
memory usage: 304.9 KB

In [9]:
pokemon_df.describe()

,HP Base,HP Min,HP Max,Attack Base,Attack Min,Attack Max,Defense Base,Defense Min,Defense Max,Special Attack Base,Special Attack Min,Special Attack Max,Special Defense Base,Special Defense Min,Special Defense Max,Speed Base,Speed Min,Speed Max
count,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000
mean,71.512715,252.934372,346.857260,81.200984,150.161608,286.766202,75.082855,139.147662,273.295324,73.284660,135.904840,269.337162,72.498769,134.500410,267.610336,70.042658,130.081214,262.253486
std,27.525247,55.374800,55.789815,31.996584,57.603845,70.391623,30.746923,55.352990,67.647787,32.720042,58.903883,72.000789,27.552678,49.597516,60.618378,30.120581,54.220835,66.290850
min,1.000000,1.000000,1.000000,5.000000,13.000000,119.000000,5.000000,13.000000,119.000000,10.000000,22.000000,130.000000,20.000000,40.000000,152.000000,5.000000,13.000000,119.000000
25%,52.500000,215.000000,309.000000,57.500000,107.500000,235.000000,52.000000,98.000000,223.000000,50.000000,94.000000,218.000000,51.000000,96.000000,221.000000,45.000000,85.000000,207.000000
50%,70.000000,250.000000,344.000000,80.000000,148.000000,284.000000,70.000000,130.000000,262.000000,65.000000,121.000000,251.000000,70.000000,130.000000,262.000000,68.000000,126.000000,258.000000
75%,85.000000,280.000000,374.000000,100.000000,184.000000,328.000000,91.000000,168.000000,309.000000,95.000000,175.000000,317.000000,90.000000,166.000000,306.000000,91.000000,168.000000,309.000000
max,255.000000,620.000000,714.000000,190.000000,346.000000,526.000000,250.000000,454.000000,658.000000,194.000000,353.000000,535.000000,250.000000,454.000000,658.000000,200.000000,364.000000,548.000000

## 6. Select columns

Select one column with `df["col"]` and many columns with `df[[...]]`.

In [10]:
pokemon_df["Catch Rate"].head()

0      60 (7.8% with PokéBall, full HP)
1      60 (7.8% with PokéBall, full HP)
2      60 (7.8% with PokéBall, full HP)
3      60 (7.8% with PokéBall, full HP)
4    200 (26.1% with PokéBall, full HP)
Name: Catch Rate, dtype: str

In [11]:
pokemon_df[["Pokemon", "Type", "Catch Rate"]].head()

          Pokemon        Type                          Catch Rate
0       Abomasnow  Grass, Ice    60 (7.8% with PokéBall, full HP)
1       Abomasnow  Grass, Ice    60 (7.8% with PokéBall, full HP)
2       Abomasnow  Grass, Ice    60 (7.8% with PokéBall, full HP)
3  Mega Abomasnow  Grass, Ice    60 (7.8% with PokéBall, full HP)
4            Abra     Psychic  200 (26.1% with PokéBall, full HP)

## 7. `loc` vs `iloc`

- `loc` uses labels
- `iloc` uses positions

In [12]:
student_marks = pd.DataFrame({
    "Name": ["Aman", "Riya", "Kunal", "Sara"],
    "Marks": [88, 92, 79, 95],
    "City": ["Delhi", "Pune", "Noida", "Jaipur"]
}, index=["s1", "s2", "s3", "s4"])

# loc example 1
student_marks.loc["s2"]

Name     Riya
Marks      92
City     Pune
Name: s2, dtype: object

In [13]:
# loc example 2
student_marks.loc[["s1", "s3"], ["Name", "Marks"]]

     Name  Marks
s1   Aman     88
s3  Kunal     79

In [14]:
# iloc example 1
student_marks.iloc[1]

Name     Riya
Marks      92
City     Pune
Name: s2, dtype: object

In [15]:
# iloc example 2
student_marks.iloc[0:2, 0:2]

    Name  Marks
s1  Aman     88
s2  Riya     92

## 8. Filtering rows

We can convert height text to a number and then filter the rows we want.

In [16]:
pokemon_df["Height_m"] = pokemon_df["Height"].str.split().str[0].astype(float)
filtered_df = pokemon_df[(pokemon_df["Type"] == "Grass") & (pokemon_df["Height_m"] >= 2)]

filtered_df[["Pokemon", "Type", "Height", "Height_m"]].head()

        Pokemon   Type          Height  Height_m
862   Rillaboom  Grass   2.1 m (6′11″)       2.1
918   Serperior  Grass  3.3 m (10′10″)       3.3
1042  Tangrowth  Grass   2.0 m (6′07″)       2.0

## 9. Aggregate functions

Aggregate functions give one summary value from many values.

In [17]:
pokemon_df[["HP Base", "Attack Base", "Speed Base"]].mean()

HP Base        71.512715
Attack Base    81.200984
Speed Base     70.042658
dtype: float64

In [18]:
pokemon_df["Height_m"].describe()

count    1219.000000
mean        1.384824
std         3.148103
min         0.100000
25%         0.600000
50%         1.000000
75%         1.600000
max       100.000000
Name: Height_m, dtype: float64

## 10. `groupby()`

`groupby()` lets us summarize values for each category.

In [19]:
pokemon_df["Catch Rate_num"] = pokemon_df["Catch Rate"].str.extract(r"(\d+)").astype("Int64")
pokemon_df.groupby("Type")["Catch Rate_num"].mean().sort_values(ascending=False).head(10)

Type
Dragon, Normal          190.0
Fire, Ground            185.0
Electric, Dark          180.0
Ground, Psychic         172.5
Ice, Steel              172.5
Bug                     167.2
Poison, Water      163.333333
Normal, Fairy           159.0
Dark, Normal            154.4
Bug, Ground             150.0
Name: Catch Rate_num, dtype: Float64

## 11. Data cleaning basics

These are common cleaning steps: remove missing rows, fill missing values, replace wrong text, and remove duplicates.

In [20]:
dirty_df = pd.DataFrame({
    "Name": ["A", "B", "B", None],
    "Type": ["Fire", "Dark", "Dark", None],
    "Score": [10, None, None, 20]
})

print("Original")
print(dirty_df)
print()

print("dropna on Type")
print(dirty_df.dropna(subset=["Type"]))
print()

print("fillna")
print(dirty_df.fillna({"Type": "Unknown", "Score": 0}))
print()

print("replace")
print(dirty_df.replace({"Dark": "DARK"}))
print()

print("drop_duplicates")
print(dirty_df.drop_duplicates())

Original
  Name  Type  Score
0    A  Fire   10.0
1    B  Dark    NaN
2    B  Dark    NaN
3  NaN   NaN   20.0

dropna on Type
  Name  Type  Score
0    A  Fire   10.0
1    B  Dark    NaN
2    B  Dark    NaN

fillna
  Name     Type  Score
0    A     Fire   10.0
1    B     Dark    0.0
2    B     Dark    0.0
3  NaN  Unknown   20.0

replace
  Name  Type  Score
0    A  Fire   10.0
1    B  DARK    NaN
2    B  DARK    NaN
3  NaN   NaN   20.0

drop_duplicates
  Name  Type  Score
0    A  Fire   10.0
1    B  Dark    NaN
3  NaN   NaN   20.0