# Day 4 Pandas Practice Notebook

This notebook keeps the same topics but gives more hands-on examples and ready solutions.

In [1]:
import pandas as pd
from pathlib import Path

base_path = Path(".")
csv_path = base_path / "pokemonDB_dataset.csv"
json_path = base_path / "pokemonDB_dataset.json"
pokemon_df = pd.read_csv(csv_path)
pokemon_indexed = pd.read_csv(csv_path, index_col="Pokemon")

## Practice 1 - Series from a list

Task: Create a series with custom index labels and print only values greater than 200.

In [2]:
# Solution
values = [23, 13, 223, 232, 334, 23]
series = pd.Series(values, index=["a", "b", "c", "d", "e", "f"])

print(series)
print()
print(series[series > 200])

a     23
b     13
c    223
d    232
e    334
f     23
dtype: int64

c    223
d    232
e    334
dtype: int64

## Practice 2 - Series from a dictionary

Task: Build a series from a dictionary, increase Day1 by 50, then access one value with `loc` and one with `iloc`.

In [3]:
# Solution
portfolio = {"Day1": 100, "Day2": 300, "Day3": 200}
portfolio_series = pd.Series(portfolio)
portfolio_series.loc["Day1"] += 50

print(portfolio_series)
print("loc Day1 ->", portfolio_series.loc["Day1"])
print("iloc 2 ->", portfolio_series.iloc[2])

Day1    150
Day2    300
Day3    200
dtype: int64
loc Day1 -> 150
iloc 2 -> 200

## Practice 3 - String series

Task: Create an object series of Pokemon names.

In [4]:
# Solution
pokemon_names = ["Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard"]
name_series = pd.Series(pokemon_names, index=range(1, len(pokemon_names) + 1), dtype="object")

print(name_series.dtype)
print(name_series)

object
1     Bulbasaur
2       Ivysaur
3      Venusaur
4    Charmander
5    Charmeleon
6     Charizard
dtype: object

## Practice 4 - DataFrame create, add column, add row

Task: Make a small DataFrame, add a new column, then append one more row.

In [5]:
# Solution
people = pd.DataFrame({
    "Name": ["Person1", "Person2", "Person3"],
    "Age": [23, 24, 25],
})
people["Job"] = ["Cook", "Cashier", "Driver"]
new_row = pd.DataFrame([{"Name": "Person4", "Age": 24, "Job": "Scientist"}])
people = pd.concat([people, new_row], ignore_index=True)

people

      Name  Age        Job
0  Person1   23       Cook
1  Person2   24    Cashier
2  Person3   25     Driver
3  Person4   24  Scientist

## Practice 5 - Read CSV and JSON

Task: Load both files and check their shape.

In [6]:
# Solution
json_df = pd.read_json(json_path).T.reset_index().rename(columns={"index": "Pokemon"})

print("CSV shape:", pokemon_df.shape)
print("JSON shape:", json_df.shape)
pokemon_df.head(2)

CSV shape: (1219, 32)
JSON shape: (1215, 32)

,Pokemon,Type,Species,Height,Weight,Abilities,EV Yield,Catch Rate,Base Friendship,Base Exp,...,Defense Max,Special Attack Base,Special Attack Min,Special Attack Max,Special Defense Base,Special Defense Min,Special Defense Max,Speed Base,Speed Min,Speed Max
0,Abomasnow,"Grass, Ice",Frost Tree Pokémon,2.2 m (7′03″),135.5 kg (298.7 lbs),"1. Snow Warning, Soundproof (hidden ability)","1 Attack, 1 Sp. Atk","60 (7.8% with PokéBall, full HP)",50 (normal),173,...,273,92,170,311,85,157,295,60,112,240
1,Abomasnow,"Grass, Ice",Frost Tree Pokémon,2.2 m (7′03″),135.5 kg (298.7 lbs),"1. Snow Warning, Soundproof (hidden ability)","1 Attack, 1 Sp. Atk","60 (7.8% with PokéBall, full HP)",50 (normal),173,...,273,92,170,311,85,157,295,60,112,240

## Practice 6 - `head()`, `tail()`, `info()`, `describe()`

Task: Use all four quick-look methods.

In [7]:
# Solution
print("head()")
print(pokemon_df.head(3))
print()

print("tail()")
print(pokemon_df.tail(3))
print()

pokemon_df.info()
print()
print(pokemon_df.describe())

head()
     Pokemon        Type             Species         Height  \
0  Abomasnow  Grass, Ice  Frost Tree Pokémon  2.2 m (7′03″)
1  Abomasnow  Grass, Ice  Frost Tree Pokémon  2.2 m (7′03″)
2  Abomasnow  Grass, Ice  Frost Tree Pokémon  2.2 m (7′03″)

                 Weight                                     Abilities  \
0  135.5 kg (298.7 lbs)  1. Snow Warning, Soundproof (hidden ability)
1  135.5 kg (298.7 lbs)  1. Snow Warning, Soundproof (hidden ability)
2  135.5 kg (298.7 lbs)  1. Snow Warning, Soundproof (hidden ability)

              EV Yield                        Catch Rate Base Friendship  \
0  1 Attack, 1 Sp. Atk  60 (7.8% with PokéBall, full HP)     50 (normal)
1  1 Attack, 1 Sp. Atk  60 (7.8% with PokéBall, full HP)     50 (normal)
2  1 Attack, 1 Sp. Atk  60 (7.8% with PokéBall, full HP)     50 (normal)

  Base Exp  ... Defense Max Special Attack Base Special Attack Min  \
0      173  ...         273                  92                170
1      173  ...         273                  92                170
2      173  ...         273                  92                170

  Special Attack Max  Special Defense Base  Special Defense Min  \
0                311                    85                  157
1                311                    85                  157
2                311                    85                  157

   Special Defense Max  Speed Base  Speed Min  Speed Max
0                  295          60        112        240
1                  295          60        112        240
2                  295          60        112        240

[3 rows x 32 columns]

tail()
                     Pokemon            Type        Species          Height  \
1216  Zygarde Complete Forme  Dragon, Ground  Order Pokémon  4.5 m (14′09″)
1217  Zygarde Complete Forme  Dragon, Ground  Order Pokémon  4.5 m (14′09″)
1218  Zygarde Complete Forme  Dragon, Ground  Order Pokémon  4.5 m (14′09″)

                     Weight           Abilities EV Yield  \
1216  610.0 kg (1344.8 lbs)  1. Power Construct     3 HP
1217  610.0 kg (1344.8 lbs)  1. Power Construct     3 HP
1218  610.0 kg (1344.8 lbs)  1. Power Construct     3 HP

                           Catch Rate        Base Friendship Base Exp  ...  \
1216  3 (0.4% with PokéBall, full HP)  0 (lower than normal)      319  ...
1217  3 (0.4% with PokéBall, full HP)  0 (lower than normal)      319  ...
1218  3 (0.4% with PokéBall, full HP)  0 (lower than normal)      319  ...

     Defense Max Special Attack Base Special Attack Min Special Attack Max  \
1216         375                  91                168                309
1217         375                  91                168                309
1218         375                  91                168                309

      Special Defense Base  Special Defense Min  Special Defense Max  \
1216                    95                  175                  317
1217                    95                  175                  317
1218                    95                  175                  317

      Speed Base  Speed Min  Speed Max
1216          85        157        295
1217          85        157        295
1218          85        157        295

[3 rows x 32 columns]

<class 'pandas.DataFrame'>
RangeIndex: 1219 entries, 0 to 1218
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Pokemon               1219 non-null   str
 1   Type                  1219 non-null   str
 2   Species               1219 non-null   str
 3   Height                1219 non-null   str
 4   Weight                1219 non-null   str
 5   Abilities             1219 non-null   str
 6   EV Yield              1219 non-null   str
 7   Catch Rate            1219 non-null   str
 8   Base Friendship       1219 non-null   str
 9   Base Exp              1219 non-null   str
 10  Growth Rate           1219 non-null   str
 11  Egg Groups            1219 non-null   str
 12  Gender                1219 non-null   str
 13  Egg Cycles            1219 non-null   str
 14  HP Base               1219 non-null   int64
 15  HP Min                1219 non-null   int64
 16  HP Max                1219 non-null   int64
 17  Attack Base           1219 non-null   int64
 18  Attack Min            1219 non-null   int64
 19  Attack Max            1219 non-null   int64
 20  Defense Base          1219 non-null   int64
 21  Defense Min           1219 non-null   int64
 22  Defense Max           1219 non-null   int64
 23  Special Attack Base   1219 non-null   int64
 24  Special Attack Min    1219 non-null   int64
 25  Special Attack Max    1219 non-null   int64
 26  Special Defense Base  1219 non-null   int64
 27  Special Defense Min   1219 non-null   int64
 28  Special Defense Max   1219 non-null   int64
 29  Speed Base            1219 non-null   int64
 30  Speed Min             1219 non-null   int64
 31  Speed Max             1219 non-null   int64
dtypes: int64(18), str(14)
memory usage: 304.9 KB

           HP Base       HP Min       HP Max  Attack Base   Attack Min  \
count  1219.000000  1219.000000  1219.000000  1219.000000  1219.000000
mean     71.512715   252.934372   346.857260    81.200984   150.161608
std      27.525247    55.374800    55.789815    31.996584    57.603845
min       1.000000     1.000000     1.000000     5.000000    13.000000
25%      52.500000   215.000000   309.000000    57.500000   107.500000
50%      70.000000   250.000000   344.000000    80.000000   148.000000
75%      85.000000   280.000000   374.000000   100.000000   184.000000
max     255.000000   620.000000   714.000000   190.000000   346.000000

        Attack Max  Defense Base  Defense Min  Defense Max  \
count  1219.000000   1219.000000  1219.000000  1219.000000
mean    286.766202     75.082855   139.147662   273.295324
std      70.391623     30.746923    55.352990    67.647787
min     119.000000      5.000000    13.000000   119.000000
25%     235.000000     52.000000    98.000000   223.000000
50%     284.000000     70.000000   130.000000   262.000000
75%     328.000000     91.000000   168.000000   309.000000
max     526.000000    250.000000   454.000000   658.000000

       Special Attack Base  Special Attack Min  Special Attack Max  \
count          1219.000000         1219.000000         1219.000000
mean             73.284660          135.904840          269.337162
std              32.720042           58.903883           72.000789
min              10.000000           22.000000          130.000000
25%              50.000000           94.000000          218.000000
50%              65.000000          121.000000          251.000000
75%              95.000000          175.000000          317.000000
max             194.000000          353.000000          535.000000

       Special Defense Base  Special Defense Min  Special Defense Max  \
count           1219.000000          1219.000000          1219.000000
mean              72.498769           134.500410           267.610336
std               27.552678            49.597516            60.618378
min               20.000000            40.000000           152.000000
25%               51.000000            96.000000           221.000000
50%               70.000000           130.000000           262.000000
75%               90.000000           166.000000           306.000000
max              250.000000           454.000000           658.000000

        Speed Base    Speed Min    Speed Max
count  1219.000000  1219.000000  1219.000000
mean     70.042658   130.081214   262.253486
std      30.120581    54.220835    66.290850
min       5.000000    13.000000   119.000000
25%      45.000000    85.000000   207.000000
50%      68.000000   126.000000   258.000000
75%      91.000000   168.000000   309.000000
max     200.000000   364.000000   548.000000

## Practice 7 - Column selection

Task: Select one column and then multiple columns.

In [8]:
# Solution
print(pokemon_df["Catch Rate"].head())
print()
print(pokemon_df[["Pokemon", "Type", "Catch Rate"]].head())

0      60 (7.8% with PokéBall, full HP)
1      60 (7.8% with PokéBall, full HP)
2      60 (7.8% with PokéBall, full HP)
3      60 (7.8% with PokéBall, full HP)
4    200 (26.1% with PokéBall, full HP)
Name: Catch Rate, dtype: str

          Pokemon        Type                          Catch Rate
0       Abomasnow  Grass, Ice    60 (7.8% with PokéBall, full HP)
1       Abomasnow  Grass, Ice    60 (7.8% with PokéBall, full HP)
2       Abomasnow  Grass, Ice    60 (7.8% with PokéBall, full HP)
3  Mega Abomasnow  Grass, Ice    60 (7.8% with PokéBall, full HP)
4            Abra     Psychic  200 (26.1% with PokéBall, full HP)

## Practice 8 - `loc` examples

Task: Use `loc` two times with label-based selection.

In [9]:
# Solution
print(pokemon_indexed.loc["Mewtwo"])
print()
print(pokemon_indexed.loc[["Mewtwo", "Pikachu"], ["Height", "Weight"]])

Type                                                  Psychic
Species                                       Genetic Pokémon
Height                                          2.0 m (6′07″)
Weight                                   122.0 kg (269.0 lbs)
Abilities               1. Pressure, Unnerve (hidden ability)
EV Yield                                            3 Sp. Atk
Catch Rate                    3 (0.4% with PokéBall, full HP)
Base Friendship                         0 (lower than normal)
Base Exp                                                  340
Growth Rate                                              Slow
Egg Groups                                       Undiscovered
Gender                                             Genderless
Egg Cycles                          120 (30,584–30,840 steps)
HP Base                                                   106
HP Min                                                    322
HP Max                                                    416
Attack Base                                               110
Attack Min                                                202
Attack Max                                                350
Defense Base                                               90
Defense Min                                               166
Defense Max                                               306
Special Attack Base                                       154
Special Attack Min                                        281
Special Attack Max                                        447
Special Defense Base                                       90
Special Defense Min                                       166
Special Defense Max                                       306
Speed Base                                                130
Speed Min                                                 238
Speed Max                                                 394
Name: Mewtwo, dtype: object

                Height                Weight
Pokemon
Mewtwo   2.0 m (6′07″)  122.0 kg (269.0 lbs)
Pikachu  0.4 m (1′04″)     6.0 kg (13.2 lbs)

## Practice 9 - `iloc` examples

Task: Use `iloc` two times with position-based selection.

In [10]:
# Solution
print(pokemon_df.iloc[0])
print()
print(pokemon_df.iloc[0:3, 0:4])

Pokemon                                                    Abomasnow
Type                                                      Grass, Ice
Species                                           Frost Tree Pokémon
Height                                                 2.2 m (7′03″)
Weight                                          135.5 kg (298.7 lbs)
Abilities               1. Snow Warning, Soundproof (hidden ability)
EV Yield                                         1 Attack, 1 Sp. Atk
Catch Rate                          60 (7.8% with PokéBall, full HP)
Base Friendship                                          50 (normal)
Base Exp                                                         173
Growth Rate                                                     Slow
Egg Groups                                            Grass, Monster
Gender                                          50% male, 50% female
Egg Cycles                                    20 (4,884–5,140 steps)
HP Base                                                           90
HP Min                                                           290
HP Max                                                           384
Attack Base                                                       92
Attack Min                                                       170
Attack Max                                                       311
Defense Base                                                      75
Defense Min                                                      139
Defense Max                                                      273
Special Attack Base                                               92
Special Attack Min                                               170
Special Attack Max                                               311
Special Defense Base                                              85
Special Defense Min                                              157
Special Defense Max                                              295
Speed Base                                                        60
Speed Min                                                        112
Speed Max                                                        240
Name: 0, dtype: object

     Pokemon        Type             Species         Height
0  Abomasnow  Grass, Ice  Frost Tree Pokémon  2.2 m (7′03″)
1  Abomasnow  Grass, Ice  Frost Tree Pokémon  2.2 m (7′03″)
2  Abomasnow  Grass, Ice  Frost Tree Pokémon  2.2 m (7′03″)

## Practice 10 - Filtering rows

Task: Find Pokemon with type Grass and height greater than or equal to 2 meters.

In [11]:
# Solution
pokemon_df["Height_m"] = pokemon_df["Height"].str.split().str[0].astype(float)
filtered_df = pokemon_df[(pokemon_df["Type"] == "Grass") & (pokemon_df["Height_m"] >= 2)]

print(filtered_df[["Pokemon", "Type", "Height", "Height_m"]].head(10))

        Pokemon   Type          Height  Height_m
862   Rillaboom  Grass   2.1 m (6′11″)       2.1
918   Serperior  Grass  3.3 m (10′10″)       3.3
1042  Tangrowth  Grass   2.0 m (6′07″)       2.0

## Practice 11 - Aggregate functions

Task: Count values and find mean, sum, min, and max for height.

In [12]:
# Solution
height_only = pokemon_df.copy()
height_only["Height"] = height_only["Height"].str.split().str[0].astype(float)

print(height_only.count())
print()
print("mean ->", height_only["Height"].mean())
print("sum ->", height_only["Height"].sum())
print("min ->", height_only["Height"].min())
print("max ->", height_only["Height"].max())

Pokemon                 1219
Type                    1219
Species                 1219
Height                  1219
Weight                  1219
Abilities               1219
EV Yield                1219
Catch Rate              1219
Base Friendship         1219
Base Exp                1219
Growth Rate             1219
Egg Groups              1219
Gender                  1219
Egg Cycles              1219
HP Base                 1219
HP Min                  1219
HP Max                  1219
Attack Base             1219
Attack Min              1219
Attack Max              1219
Defense Base            1219
Defense Min             1219
Defense Max             1219
Special Attack Base     1219
Special Attack Min      1219
Special Attack Max      1219
Special Defense Base    1219
Special Defense Min     1219
Special Defense Max     1219
Speed Base              1219
Speed Min               1219
Speed Max               1219
Height_m                1219
dtype: int64

mean -> 1.3848236259228874
sum -> 1688.1
min -> 0.1
max -> 100.0

## Practice 12 - `groupby()`

Task: Convert catch rate to a number and summarize it by Pokemon type.

In [13]:
# Solution
group_df = pokemon_df.copy()
group_df["Catch Rate"] = group_df["Catch Rate"].str.extract(r"(\d+)").astype("Int64")
group = group_df.groupby("Type")["Catch Rate"]

print(group.mean())
print()
print(group.sum())
print()
print(group.min())

Type
Bug                   167.2
Bug, Dark              30.0
Bug, Electric         107.5
Bug, Fairy            132.5
Bug, Fighting          42.0
                    ...
Water, Ice            56.25
Water, Poison     98.333333
Water, Psychic    92.857143
Water, Rock            50.0
Water, Steel           45.0
Name: Catch Rate, Length: 221, dtype: Float64

Type
Bug               4180
Bug, Dark           30
Bug, Electric      430
Bug, Fairy         265
Bug, Fighting      210
                  ...
Water, Ice         225
Water, Poison      295
Water, Psychic     650
Water, Rock        250
Water, Steel        45
Name: Catch Rate, Length: 221, dtype: Int64

Type
Bug               45
Bug, Dark         30
Bug, Electric     45
Bug, Fairy        75
Bug, Fighting     30
                  ..
Water, Ice        45
Water, Poison     45
Water, Psychic    60
Water, Rock       25
Water, Steel      45
Name: Catch Rate, Length: 221, dtype: Int64

## Practice 13 - Data cleaning

Task: Try common cleaning operations on a small messy DataFrame.

In [14]:
# Solution
clean_df = pd.DataFrame({
    "Pokemon": ["A", "B", "B", None],
    "Type": ["Dark", "Dark", "Dark", None],
    "Score": [10, None, None, 20]
})

print("Original")
print(clean_df)
print()

print("dropna(subset=[\"Type\"])")
print(clean_df.dropna(subset=["Type"]))
print()

print("fillna")
print(clean_df.fillna({"Type": "Unknown", "Score": 0}))
print()

print("replace")
print(clean_df.replace({"Dark": "DARK"}))
print()

print("drop_duplicates")
print(clean_df.drop_duplicates())

Original
  Pokemon  Type  Score
0       A  Dark   10.0
1       B  Dark    NaN
2       B  Dark    NaN
3     NaN   NaN   20.0

dropna(subset=["Type"])
  Pokemon  Type  Score
0       A  Dark   10.0
1       B  Dark    NaN
2       B  Dark    NaN

fillna
  Pokemon     Type  Score
0       A     Dark   10.0
1       B     Dark    0.0
2       B     Dark    0.0
3     NaN  Unknown   20.0

replace
  Pokemon  Type  Score
0       A  DARK   10.0
1       B  DARK    NaN
2       B  DARK    NaN
3     NaN   NaN   20.0

drop_duplicates
  Pokemon  Type  Score
0       A  Dark   10.0
1       B  Dark    NaN
3     NaN   NaN   20.0